/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vocabuilderforserver;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.ServerSocket;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 *
 * @author Md Saddam Hossain
 */
public class StartMenu extends javax.swing.JFrame {

    private static ServerSocket server; // server socket
    public static Socket connection; // connection to client
    private int connectionFlag, entryFlag = 0;
    public javax.swing.JPanel jPanel2ForStartMenu;
    public static StartMenu startMenu;

    /**
     * Creates new form StartMenu
     */
    public StartMenu() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1ForStartMenu = new javax.swing.JPanel();
        jLabel1ForPort = new javax.swing.JLabel();
        jTextField1ForServerPort = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1ForStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vocabuilder");
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        jPanel1ForStartMenu.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1ForStartMenu.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1ForStartMenu.setMaximumSize(new java.awt.Dimension(800, 650));
        jPanel1ForStartMenu.setMinimumSize(new java.awt.Dimension(800, 650));
        jPanel1ForStartMenu.setPreferredSize(new java.awt.Dimension(800, 650));
        jPanel1ForStartMenu.setLayout(null);

        jLabel1ForPort.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1ForPort.setText("Port    :");
        jPanel1ForStartMenu.add(jLabel1ForPort);
        jLabel1ForPort.setBounds(262, 252, 47, 15);
        jPanel1ForStartMenu.add(jTextField1ForServerPort);
        jTextField1ForServerPort.setBounds(319, 250, 125, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Server");
        jPanel1ForStartMenu.add(jLabel2);
        jLabel2.setBounds(319, 125, 77, 22);

        jButton1ForStart.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1ForStart.setText("Start");
        jButton1ForStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ForStartActionPerformed(evt);
            }
        });
        jPanel1ForStartMenu.add(jButton1ForStart);
        jButton1ForStart.setBounds(291, 386, 84, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1ForStartMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1ForStartMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ForStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ForStartActionPerformed
        // TODO add your handling code here:
        try {
            if (entryFlag == 0) {
                try // set up server to receive connections; process connections
                {
                    connectionFlag = 1;
                    server = new ServerSocket(Integer.parseInt(jTextField1ForServerPort.getText()), 100); // create ServerSocket
                } catch (Exception e) {
                    connectionFlag = 0;
                    JOptionPane.showMessageDialog(null, "Port Address is invalid.", "Error", JOptionPane.ERROR_MESSAGE);
                    System.out.println("Exception in okButtonActionPerformed, after initializing the server variable");
                    e.printStackTrace();
                }

                if (connectionFlag == 1) {
                   // startMenu.getContentPane().remove(jPanel1ForStartMenu);
                    //startMenu.getContentPane().add(SendData.jPanel1ForSendData);
                    //startMenu.repaint();
                    jTextField1ForServerPort.setEditable(false);
                    entryFlag = 1;

                    Thread thread = new Thread() {
                        public void run() {
                            try {
                                runServer();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    };

                    thread.start();
                }
            }
        } catch (Exception e) {
            System.out.println("Exception in okButtonActionPerformed()");
            e.printStackTrace();
        }
        startMenu.getContentPane().remove(jPanel1ForStartMenu);
        new SendData();
        startMenu.getContentPane().add(SendData.jPanel1ForSendData);
        startMenu.repaint();
    }//GEN-LAST:event_jButton1ForStartActionPerformed
    public void runServer() {

        while (true) {
            try {
                waitForConnection(); // wait for a connection
                ServerThread serverThread = new ServerThread();

            } // end try
            catch (Exception e) //changed.........................................
            {
                System.out.println("Exception in runserver method, after initializing the serverThread");
                e.printStackTrace();
            } // end catch
        }
    }

    private void waitForConnection() throws IOException {
        System.out.println("Waiting for connection...........");
        connection = server.accept(); // allow server to accept connection
        System.out.println("Connection receieved from client.........");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                startMenu = new StartMenu();
                startMenu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1ForStart;
    private javax.swing.JLabel jLabel1ForPort;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1ForStartMenu;
    private javax.swing.JTextField jTextField1ForServerPort;
    // End of variables declaration//GEN-END:variables
}
