/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vocabuilder;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/***
 * This class been created for the About section of this application.
 * @author Moqsadur Rahman
 */

public class About extends javax.swing.JFrame {
    public static javax.swing.JPanel jPanlel2OfAbout;
    /**
     * Creates new form ABOUT
     */
    public About() {
        initComponents();
        jPanlel2OfAbout = jPanel1OfAbout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1OfAbout = new javax.swing.JPanel();
        jLabelForAbout = new javax.swing.JLabel();
        jLabelForName = new javax.swing.JLabel();
        jLabelForReg = new javax.swing.JLabel();
        jLabelForDept = new javax.swing.JLabel();
        jLabelForContact = new javax.swing.JLabel();
        jButtonForBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Typing Improver");
        setResizable(false);

        jPanel1OfAbout.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1OfAbout.setPreferredSize(new java.awt.Dimension(800, 650));
        jPanel1OfAbout.setLayout(null);

        jLabelForAbout.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelForAbout.setText("ABOUT-->");
        jPanel1OfAbout.add(jLabelForAbout);
        jLabelForAbout.setBounds(300, 40, 200, 50);

        jLabelForName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelForName.setText("Md Saddam Hossain");
        jPanel1OfAbout.add(jLabelForName);
        jLabelForName.setBounds(100, 220, 260, 30);

        jLabelForReg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelForReg.setText("Reg No : 2012331068");
        jPanel1OfAbout.add(jLabelForReg);
        jLabelForReg.setBounds(100, 250, 280, 30);

        jLabelForDept.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelForDept.setText("Dept. of CSE, SUST");
        jPanel1OfAbout.add(jLabelForDept);
        jLabelForDept.setBounds(100, 350, 240, 30);

        jLabelForContact.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelForContact.setText("Contact : mshossaincse@gmail.com");
        jPanel1OfAbout.add(jLabelForContact);
        jLabelForContact.setBounds(100, 380, 330, 30);

        jButtonForBack.setText("Back");
        jButtonForBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForBackActionPerformed(evt);
            }
        });
        jPanel1OfAbout.add(jButtonForBack);
        jButtonForBack.setBounds(30, 30, 110, 23);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Dipaloke Saha");
        jPanel1OfAbout.add(jLabel1);
        jLabel1.setBounds(100, 280, 200, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Reg No : 2012331068");
        jPanel1OfAbout.add(jLabel2);
        jLabel2.setBounds(100, 320, 230, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1OfAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1OfAbout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***
     * By clicking this button user will be able to go the start menu
     * @param evt is a reference of ActionEvent. 
     */
    
    private void jButtonForBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForBackActionPerformed
        // TODO add your handling code here:
     
        StartMenu.startMenu.getContentPane().remove(About.jPanlel2OfAbout);
        StartMenu.startMenu.getContentPane().add(StartMenu.startMenu.jPanel2OfStartMenu);
        StartMenu.startMenu.repaint();
    }//GEN-LAST:event_jButtonForBackActionPerformed

    /***
     * This method has been created for running this class file separately which is actually not mandatory.
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(About.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new About().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelForAbout;
    private javax.swing.JLabel jLabelForContact;
    private javax.swing.JLabel jLabelForDept;
    private javax.swing.JLabel jLabelForName;
    private javax.swing.JLabel jLabelForReg;
    private javax.swing.JPanel jPanel1OfAbout;
    // End of variables declaration//GEN-END:variables
}
