/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vocabuilder;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;



public class Tips extends javax.swing.JFrame {
    public static javax.swing.JPanel jPanel2OfTips;
    /**
     * Creates new form TIPS
     */
    public Tips() {
        initComponents();
        jPanel2OfTips = jPanel1OfTips;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1OfTips = new javax.swing.JPanel();
        jButtonForBack = new javax.swing.JButton();
        jLabelForTips = new javax.swing.JLabel();
        jScrollPane1ForTips = new javax.swing.JScrollPane();
        jTextArea1ForTips = new javax.swing.JTextArea();
        jScrollPane2ForTips = new javax.swing.JScrollPane();
        jTextArea2ForTips = new javax.swing.JTextArea();
        jScrollPane3ForTips = new javax.swing.JScrollPane();
        jTextArea3ForTips = new javax.swing.JTextArea();
        jScrollPane5ForTips = new javax.swing.JScrollPane();
        jTextArea5ForTips = new javax.swing.JTextArea();
        jScrollPane4ForTips = new javax.swing.JScrollPane();
        jTextArea4ForTips = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1OfTips.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1OfTips.setPreferredSize(new java.awt.Dimension(800, 650));
        jPanel1OfTips.setLayout(null);

        jButtonForBack.setText("Back");
        jButtonForBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForBackActionPerformed(evt);
            }
        });
        jPanel1OfTips.add(jButtonForBack);
        jButtonForBack.setBounds(20, 10, 100, 23);

        jLabelForTips.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabelForTips.setText("TIPS -->");
        jPanel1OfTips.add(jLabelForTips);
        jLabelForTips.setBounds(310, 10, 200, 40);

        jTextArea1ForTips.setEditable(false);
        jTextArea1ForTips.setBackground(new java.awt.Color(153, 255, 153));
        jTextArea1ForTips.setColumns(20);
        jTextArea1ForTips.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextArea1ForTips.setRows(5);
        jScrollPane1ForTips.setViewportView(jTextArea1ForTips);

        jPanel1OfTips.add(jScrollPane1ForTips);
        jScrollPane1ForTips.setBounds(10, 70, 770, 110);

        jTextArea2ForTips.setEditable(false);
        jTextArea2ForTips.setBackground(new java.awt.Color(255, 153, 153));
        jTextArea2ForTips.setColumns(20);
        jTextArea2ForTips.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextArea2ForTips.setRows(5);
        jScrollPane2ForTips.setViewportView(jTextArea2ForTips);

        jPanel1OfTips.add(jScrollPane2ForTips);
        jScrollPane2ForTips.setBounds(10, 190, 770, 110);

        jTextArea3ForTips.setEditable(false);
        jTextArea3ForTips.setBackground(new java.awt.Color(153, 255, 204));
        jTextArea3ForTips.setColumns(20);
        jTextArea3ForTips.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextArea3ForTips.setRows(5);
        jScrollPane3ForTips.setViewportView(jTextArea3ForTips);

        jPanel1OfTips.add(jScrollPane3ForTips);
        jScrollPane3ForTips.setBounds(10, 310, 770, 90);

        jTextArea5ForTips.setEditable(false);
        jTextArea5ForTips.setBackground(new java.awt.Color(153, 153, 255));
        jTextArea5ForTips.setColumns(20);
        jTextArea5ForTips.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextArea5ForTips.setRows(5);
        jScrollPane5ForTips.setViewportView(jTextArea5ForTips);

        jPanel1OfTips.add(jScrollPane5ForTips);
        jScrollPane5ForTips.setBounds(10, 490, 770, 110);

        jTextArea4ForTips.setEditable(false);
        jTextArea4ForTips.setBackground(new java.awt.Color(255, 153, 255));
        jTextArea4ForTips.setColumns(20);
        jTextArea4ForTips.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jTextArea4ForTips.setRows(5);
        jScrollPane4ForTips.setViewportView(jTextArea4ForTips);

        jPanel1OfTips.add(jScrollPane4ForTips);
        jScrollPane4ForTips.setBounds(10, 410, 770, 70);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1OfTips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1OfTips, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /***
     * By clicking this button user will be able to go the start menu
     * @param evt is a reference of ActionEvent. 
     */
    
    private void jButtonForBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForBackActionPerformed
        // TODO add your handling code here:
        try {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File("button.wav").getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        }
        catch(Exception ex){
            System.out.println("ERROR in Tips!!!");
        }
        StartMenu.startMenu.getContentPane().remove(Tips.jPanel2OfTips);
        StartMenu.startMenu.getContentPane().add(StartMenu.jPanel2OfStartMenu);
        StartMenu.startMenu.repaint();
    }//GEN-LAST:event_jButtonForBackActionPerformed

    /***
     * This method has been created for running this class file separately which is actually not mandatory.
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tips().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonForBack;
    private javax.swing.JLabel jLabelForTips;
    private javax.swing.JPanel jPanel1OfTips;
    private javax.swing.JScrollPane jScrollPane1ForTips;
    private javax.swing.JScrollPane jScrollPane2ForTips;
    private javax.swing.JScrollPane jScrollPane3ForTips;
    private javax.swing.JScrollPane jScrollPane4ForTips;
    private javax.swing.JScrollPane jScrollPane5ForTips;
    private javax.swing.JTextArea jTextArea1ForTips;
    private javax.swing.JTextArea jTextArea2ForTips;
    private javax.swing.JTextArea jTextArea3ForTips;
    private javax.swing.JTextArea jTextArea4ForTips;
    private javax.swing.JTextArea jTextArea5ForTips;
    // End of variables declaration//GEN-END:variables
}
